/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdfareaextractortoexcel;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;

/**
 *
 * @author Ivan
 */
public class pdfareaextractortoexcel extends javax.swing.JFrame {

    private javax.swing.ButtonGroup btnGroupStructure;
    private javax.swing.ButtonGroup btnGroupPages;
    private BufferedImage currentImage;
    private PDDocument pdfDocument;
    private PDFPagePanel pagePanel;
    private String PDFLink;
    /**
     * Creates new form pdfareaextractortoexcel
     */
    public pdfareaextractortoexcel() {
        initComponents();

        // Configuración del frame principal
        setTitle("PDF Area Extractor to Excel (Java)");
        setExtendedState(pdfareaextractortoexcel.MAXIMIZED_BOTH);
        splMain.setResizeWeight(0.5);
        splMain.setEnabled(false);
        
        splRightPanel.setResizeWeight(0.5);
        splRightPanel.setEnabled(false);

        // Imagen en blanco temporal
        BufferedImage placeholderImage = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);

        // Creación del PDFPagePanel con la imagen vacía
        pagePanel = new PDFPagePanel(placeholderImage);
        pagePanel.setZoom(1.0);
        pagePanel.setCanSelect(false);

        scrPdfViewer.setViewportView(pagePanel);
        
        // Configuración de btnGroupStructure
        btnGroupStructure = new javax.swing.ButtonGroup();
        btnGroupStructure.add(rdbStructure1);
        btnGroupStructure.add(rdbStructure2);
        btnGroupStructure.add(rdbStructure3);

        // Configuración de btnGroupPages
        btnGroupPages = new javax.swing.ButtonGroup();
        btnGroupPages.add(tglPag1);
        btnGroupPages.add(tglPag2);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splMain = new javax.swing.JSplitPane();
        pnlLeft = new javax.swing.JPanel();
        btnSelector = new javax.swing.JButton();
        txfLink = new javax.swing.JTextField();
        pnlStructure = new javax.swing.JPanel();
        pnlStructure1 = new javax.swing.JPanel();
        rdbStructure1 = new javax.swing.JRadioButton();
        imgPage1 = new javax.swing.JLabel();
        imgPage2 = new javax.swing.JLabel();
        pnlStructure2 = new javax.swing.JPanel();
        rdbStructure2 = new javax.swing.JRadioButton();
        imgPage3 = new javax.swing.JLabel();
        pnlStructure3 = new javax.swing.JPanel();
        rdbStructure3 = new javax.swing.JRadioButton();
        imgPage4 = new javax.swing.JLabel();
        imgPage5 = new javax.swing.JLabel();
        lblStructure = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        scrPdfViewer = new javax.swing.JScrollPane();
        splRightPanel = new javax.swing.JSplitPane();
        tglPag1 = new javax.swing.JToggleButton();
        tglPag2 = new javax.swing.JToggleButton();
        sldRightPanel = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splMain.setDividerLocation(500);

        pnlLeft.setPreferredSize(new java.awt.Dimension(400, 500));

        btnSelector.setText("Cargar archivo");
        btnSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectorActionPerformed(evt);
            }
        });

        pnlStructure.setBackground(new java.awt.Color(200, 200, 200));
        pnlStructure.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlStructure1.setBackground(new java.awt.Color(200, 200, 200));

        rdbStructure1.setText("<html>Todos los datos<br>en cada página</html>");

        imgPage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphicresources/todoPorCara.png"))); // NOI18N
        imgPage1.setText("jLabel1");

        imgPage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphicresources/blanco.png"))); // NOI18N
        imgPage2.setText("jLabel2");

        javax.swing.GroupLayout pnlStructure1Layout = new javax.swing.GroupLayout(pnlStructure1);
        pnlStructure1.setLayout(pnlStructure1Layout);
        pnlStructure1Layout.setHorizontalGroup(
            pnlStructure1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStructure1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbStructure1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlStructure1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgPage2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStructure1Layout.setVerticalGroup(
            pnlStructure1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStructure1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlStructure1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgPage1)
                    .addComponent(imgPage2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbStructure1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStructure2.setBackground(new java.awt.Color(200, 200, 200));

        rdbStructure2.setText("<html>Todos los datos<br>cada dos páginas</html>");

        imgPage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphicresources/todoPorCara.png"))); // NOI18N
        imgPage3.setText("jLabel3");

        javax.swing.GroupLayout pnlStructure2Layout = new javax.swing.GroupLayout(pnlStructure2);
        pnlStructure2.setLayout(pnlStructure2Layout);
        pnlStructure2Layout.setHorizontalGroup(
            pnlStructure2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStructure2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbStructure2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStructure2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgPage3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStructure2Layout.setVerticalGroup(
            pnlStructure2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStructure2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgPage3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbStructure2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStructure3.setBackground(new java.awt.Color(200, 200, 200));

        rdbStructure3.setText("<html>Datos por un lado<br>y votos por el otro</html>");

        imgPage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphicresources/datos.png"))); // NOI18N
        imgPage4.setText("jLabel4");

        imgPage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphicresources/tabla.png"))); // NOI18N
        imgPage5.setText("jLabel5");

        javax.swing.GroupLayout pnlStructure3Layout = new javax.swing.GroupLayout(pnlStructure3);
        pnlStructure3.setLayout(pnlStructure3Layout);
        pnlStructure3Layout.setHorizontalGroup(
            pnlStructure3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStructure3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlStructure3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbStructure3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlStructure3Layout.createSequentialGroup()
                        .addComponent(imgPage4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgPage5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStructure3Layout.setVerticalGroup(
            pnlStructure3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStructure3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(pnlStructure3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgPage4)
                    .addComponent(imgPage5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbStructure3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlStructureLayout = new javax.swing.GroupLayout(pnlStructure);
        pnlStructure.setLayout(pnlStructureLayout);
        pnlStructureLayout.setHorizontalGroup(
            pnlStructureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStructureLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(pnlStructure1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(pnlStructure2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(pnlStructure3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlStructureLayout.setVerticalGroup(
            pnlStructureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStructureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStructureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlStructure2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStructure3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlStructure1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblStructure.setText("Estructura del documento");

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addComponent(lblStructure, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addComponent(btnSelector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfLink))
                    .addComponent(pnlStructure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelector)
                    .addComponent(txfLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStructure)
                .addGap(4, 4, 4)
                .addComponent(pnlStructure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        splMain.setLeftComponent(pnlLeft);

        tglPag1.setLabel("Pag. 1");
        splRightPanel.setLeftComponent(tglPag1);

        tglPag2.setLabel("Pag. 2");
        splRightPanel.setRightComponent(tglPag2);

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPdfViewer)
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addComponent(splRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(sldRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPdfViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splRightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldRightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        splMain.setRightComponent(pnlRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectorActionPerformed

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos PDF", "pdf");
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        int result = chooser.showOpenDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        PDFLink = chooser.getSelectedFile().getAbsolutePath();
        txfLink.setText(PDFLink);
        
        PDDocument doc = null;
        File archivo = new File(PDFLink);
        try {
            doc = Loader.loadPDF(archivo);
        } catch (org.apache.pdfbox.pdmodel.encryption.InvalidPasswordException ex) {
            String password = JOptionPane.showInputDialog(
                this,
                "Este archivo PDF está protegido con contraseña.\nPor favor, introdúcela:",
                "Contraseña requerida",
                JOptionPane.QUESTION_MESSAGE
            );
            if (password == null) {
                JOptionPane.showMessageDialog(
                    this,
                    "No se cargó el PDF porque no se proporcionó la contraseña.",
                    "Operación cancelada",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            try {
                doc = Loader.loadPDF(archivo, password);
            } catch (org.apache.pdfbox.pdmodel.encryption.InvalidPasswordException ex2) {
                JOptionPane.showMessageDialog(
                    this,
                    "Contraseña incorrecta. No se pudo abrir el PDF.",
                    "Error de Contraseña",
                    JOptionPane.ERROR_MESSAGE
                );
                return;
            } catch (IOException ioe) {
                ioe.printStackTrace();
                JOptionPane.showMessageDialog(
                    this,
                    "Error al abrir el PDF cifrado:\n" + ioe.getMessage(),
                    "Error interno",
                    JOptionPane.ERROR_MESSAGE
                );
                return;
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                this,
                "Error al cargar o renderizar el PDF:\n" + e.getMessage(),
                "Error interno",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        pdfDocument = doc;
        try {
            PDFRenderer renderer = new PDFRenderer(pdfDocument);
            BufferedImage img = renderer.renderImageWithDPI(0, 150);
            currentImage = img;

            pagePanel = new PDFPagePanel(img);
            //pagePanel.setOnAreaSelected(this::onAreaSelected);
            pagePanel.setCanSelect(false);
            pagePanel.setCurrentPage(0);
            //pagePanel.setSelections(selecciones.get(0));

            /*
            jList1.addListSelectionListener(ev -> {
                campoActivo = jList1.getSelectedValue();
                pagePanel.setCanSelect(campoActivo != null);
                pagePanel.repaint();
            });
            */
            
            scrPdfViewer.setViewportView(pagePanel);
            splMain.setDividerLocation(0.5);

            
            SwingUtilities.invokeLater(() -> {
                Dimension vp = scrPdfViewer.getViewport().getExtentSize();
                double initZoom = vp.width / (double) img.getWidth();
                pagePanel.setZoom(initZoom);
               
                sldRightPanel.setMinimum(50);
                sldRightPanel.setMaximum(200);
                sldRightPanel.setValue((int) (initZoom * 100));
                
            });

            sldRightPanel.addChangeListener(e -> {
                double z = sldRightPanel.getValue() / 100.0;
                pagePanel.setZoom(z);
            });

            scrPdfViewer.revalidate();
            scrPdfViewer.repaint();

        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(
                this,
                "Error al renderizar la primera página:\n" + ex.getMessage(),
                "Error interno",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSelectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pdfareaextractortoexcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pdfareaextractortoexcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pdfareaextractortoexcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pdfareaextractortoexcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pdfareaextractortoexcel().setVisible(true);
            }
        });
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelector;
    private javax.swing.JLabel imgPage1;
    private javax.swing.JLabel imgPage2;
    private javax.swing.JLabel imgPage3;
    private javax.swing.JLabel imgPage4;
    private javax.swing.JLabel imgPage5;
    private javax.swing.JLabel lblStructure;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlStructure;
    private javax.swing.JPanel pnlStructure1;
    private javax.swing.JPanel pnlStructure2;
    private javax.swing.JPanel pnlStructure3;
    private javax.swing.JRadioButton rdbStructure1;
    private javax.swing.JRadioButton rdbStructure2;
    private javax.swing.JRadioButton rdbStructure3;
    private javax.swing.JScrollPane scrPdfViewer;
    private javax.swing.JSlider sldRightPanel;
    private javax.swing.JSplitPane splMain;
    private javax.swing.JSplitPane splRightPanel;
    private javax.swing.JToggleButton tglPag1;
    private javax.swing.JToggleButton tglPag2;
    private javax.swing.JTextField txfLink;
    // End of variables declaration//GEN-END:variables
}
